# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# cat1 = Category.create(name: "Coal Fired", comments: "New York-style pizza and New Haven-style pizza are often cooked in coal-fired pizza ovens. A coal-fired oven can reach 900 °F (482 °C) and cook a pie in two to three or five minutes. Pizzerias outside of the Northeastern United States that feature coal-fired ovens are uncommon enough to be noted in travel guides. There are only five coal-fired ovens located west of the Mississippi."),
# cat2 = Category.create(name: "Commercial Gas Oven", comments: "Most commercial pizza gas ovens cook at temperatures ranging from 700 to 800 degrees."),
# cat3 = Category.create(name: "Wood Fired/Brick Oven", comments: "Wood-fire brick ovens use a small fire to heat a large solid oven. The oven holds the heat for a long time, so this type of cooking is very economical. Temperatures in a wood-fired oven can reach 800 °F (426 °C)."),
#
#
# pizza1 = Pie.create(name: "California/Gourmet Style", crust: "thin", cheese: "optional", shape: "round"),
# pizza2 = Pie.create(name: "Chicago-Style/Deep Dish", crust: "Deep-dish", cheese: "mozzarella", shape: "round", pan: "oiled steel pan"),
# pizza3 = Pie.create(name: "Chicago Thin Crust", crust: "thin", cheese: "mozzarella", shape: "round"),
# pizza4 = Pie.create(name: "Detroit Style", crust: "Deep-Dish", cheese: "mozzarella", shape: "square", pan: "oiled blue steel pan or cast iron", additional_comments: "A carmelized crust is a distinct feature of such a pizza."),
# pizza5 = Pie.create(name: "Grandma Pie", crust: "thin", cheese: "mozzarella", shape: "rectangular", pan: "olive-oil coated pan"),
# pizza6 = Pie.create(name: "Greek Style", crust: "somewhere between crunchy and thicker sicilian cousin", cheese: "mozzarella", shape: "round", pan: "oiled shallow pan"),
# pizza7 = Pie.create(name: "Italian Tomato Pie/New Jersey Style", crust: "thin", cheese: "grated romano", shape: "square", pan: "steel rectangular pan", additional_comments: "Cheese is optional."),
# pizza8 = Pie.create(name: "Neopolitan", crust: "thin", cheese: "mozzarella", shape: "round", additional_comments: "Has several different variations, such as Pizza Marinara and Pizza Margherita."),
# pizza9 = Pie.create(name: "NY Style", crust: "thin", cheese: "mozzarella", shape: "round"),
# pizza10 = Pie.create(name: "Pizza Margherita", crust: "thin", cheese: "fresh mozzarella", shape: "round", additional_comments: "Pizza Margherita is a variant of Neopolitan Pizza."),
# pizza11 = Pie.create(name: "Sicilian Style", crust: "thick", cheese: "mozzarella", shape: "rectangular"),
# pizza12 = Pie.create(name: "St. Louis Style", crust: "cracker", cheese: "provel", shape: "round", additional_comments: "Provel cheese is a combination of cheddar, Swiss and provolone cheeses."),
# pizza13 = Pie.create(name: "White Clam Pie", crust: "thin", shape: "round", cheese: "grated Romano", additional_comments: "Made with whole or chopped clams, garlic, olive oil, and oregano. Sometimes cheese is omitted."),

cat1 = Category.create(name: "California/Gourmet Style", crust: "thin", cheese: "optional", shape: "round"),
cat2 = Category.create(name: "Chicago-Style/Deep Dish", crust: "Deep-dish", cheese: "mozzarella", shape: "round", pan: "oiled steel pan"),
cat3 = Category.create(name: "Chicago Thin Crust", crust: "thin", cheese: "mozzarella", shape: "round"),
cat4 = Category.create(name: "Detroit Style", crust: "Deep-Dish", cheese: "mozzarella", shape: "square", pan: "oiled blue steel pan or cast iron", additional_comments: "A carmelized crust is a distinct feature of such a pizza."),
cat5 = Category.create(name: "Grandma Pie", crust: "thin", cheese: "mozzarella", shape: "rectangular", pan: "olive-oil coated pan"),
cat6 = Category.create(name: "Greek Style", crust: "somewhere between crunchy and thicker sicilian cousin", cheese: "mozzarella", shape: "round", pan: "oiled shallow pan"),
cat7 = Category.create(name: "Italian Tomato Pie/New Jersey Style", crust: "thin", cheese: "grated romano", shape: "square", pan: "steel rectangular pan", additional_comments: "Cheese is optional."),
cat8 = Category.create(name: "Neopolitan", crust: "thin", cheese: "mozzarella", shape: "round", additional_comments: "Has several different variations, such as Pizza Marinara and Pizza Margherita."),
cat9 = Category.create(name: "NY Style", crust: "thin", cheese: "mozzarella", shape: "round"),
cat10 = Category.create(name: "Pizza Margherita", crust: "thin", cheese: "fresh mozzarella", shape: "round", additional_comments: "Pizza Margherita is a variant of Neopolitan Pizza."),
cat11 = Category.create(name: "Sicilian Style", crust: "thick", cheese: "mozzarella", shape: "rectangular"),
cat12 = Category.create(name: "St. Louis Style", crust: "cracker", cheese: "provel", shape: "round", additional_comments: "Provel cheese is a combination of cheddar, Swiss and provolone cheeses."),
cat13 = Category.create(name: "White Clam Pie", crust: "thin", shape: "round", cheese: "grated Romano", additional_comments: "Made with whole or chopped clams, garlic, olive oil, and oregano. Sometimes cheese is omitted."),


restaurant1 = Restaurant.create(name: "Giuseppina's", neighborhood: "South Slope", borough: "Brooklyn", sit_down_or_take_out: "sit down", category_id: "8"),
restaurant2 = Restaurant.create(name: "Corner Slice at Gotham West", neighborhood: "Hell's Kitchen", borough: "Manhattan", sit_down_or_take_out: "sit down", category_id: "5"),
restaurant3 = Restaurant.create(name: "Santa Panza", neighborhood: "Bushwick", borough: "Brooklyn", sit_down_or_take_out: "sit down", category_id: "8", oven: "Wood fire"),
restaurant4 = Restaurant.create(name: "NY Pizza Suprema", neighborhood: "Midtown", borough: "Manhattan", sit_down_or_take_out: "sit down" , category_id: "9" ),
restaurant5 = Restaurant.create(name: "Ops", neighborhood: "Bushwick" , borough: "Brooklyn", sit_down_or_take_out: "sit down" , category_id: "8", oven: "Brick oven"),
restaurant6 = Restaurant.create(name: "Speedy Romeo" , neighborhood: "Clinton Hill" , borough: "Brooklyn", sit_down_or_take_out: "sit down" , category_id: "12", multiple_locations: "true" ),
restaurant7 = Restaurant.create(name: "Di Fara" , neighborhood: "Midwood", borough: "Brooklyn", sit_down_or_take_out: "sit down", category_id: "9"),
restaurant8 = Restaurant.create(name: "Price Street Pizza", neighborhood: "Nolita" , borough: "Manhattan" , sit_down_or_take_out: "sit down", category_id: "11"),
restaurant9 = Restaurant.create(name: "Lucali", neighborhood: "Carroll Gardens" , borough: "Brooklyn", sit_down_or_take_out: "sit down" , category_id: "8"),
restaurant10 = Restaurant.create(name: "Patsy's Pizzeria", neighborhood: "East Harlem" , borough: "Manhattan" , sit_down_or_take_out: "sit down", category_id: "8", oven: "Coal oven" ),
restaurant11 = Restaurant.create(name: "Motorino" , neighborhood: "East Village" , borough: "Manhattan", sit_down_or_take_out: "sit down", category_id: "8" , multiple_locations: "true"),
restaurant12 = Restaurant.create(name: "Totonno's" , neighborhood: "Coney Island" , borough: "Brooklyn", sit_down_or_take_out: "sit down", category_id: "10"),
restaurant13 = Restaurant.create(name: "Roberta's", neighborhood: "Bushwick", borough: "Brooklyn" , sit_down_or_take_out: "sit down", category_id: "8"),
restaurant14 = Restaurant.create(name: "Joe & Pat's", neighborhood: "Castleton Corners", borough: "Staten Island", sit_down_or_take_out: "sit down", category_id: "8", multiple_locations: "true" ),
restaurant15 = Restaurant.create(name: "Joe's Pizza", neighborhood: "West Village", borough: "Manhattan", sit_down_or_take_out: "standing room only", category_id: "9", multiple_locations: "true"),
restaurant16 = Restaurant.create(name: "Sal and Carmines", neighborhood: "Manhattan Valley", borough: "Manhattan", sit_down_or_take_out: "sit down", category_id: "9" ),
restaurant17 = Restaurant.create(name: "MAMA'S TOO!" , neighborhood: "Manhattan Valley" , borough: "Manhattan", sit_down_or_take_out: "sit down", category_id: "4"),
restaurant18 = Restaurant.create(name: "Paulie Gee's", neighborhood:  "Greenpoint", borough: "Brooklyn" , sit_down_or_take_out: "sit down", category_id: "8" ),


top1 = Topping.create(name: "Anchovies"),
top2 = Topping.create(name: "Artichoke"),
top3 = Topping.create(name: "Arugula"),
top4 = Topping.create(name: "Bacon"),
top5 = Topping.create(name: "Banana Peppers"),
top6 = Topping.create(name: "BBQ Chicken"),
top7 = Topping.create(name: "BBQ Sauce"),
top8 = Topping.create(name: "Broccoli"),
top9 = Topping.create(name: "Broccoli Rabe"),
top10 = Topping.create(name: "Buffalo Mozzarella"),
top11 = Topping.create(name: "Burrata Cheese"),
top12 = Topping.create(name: "Butter"),
top13 = Topping.create(name: "Black Pepper"),
top14 = Topping.create(name: "Capers"),
top15 = Topping.create(name: "Chili Flakes"),
top16 = Topping.create(name: "Chili Peppers"),
top17 = Topping.create(name: "Chopped Clams"),
top18 = Topping.create(name: "Cremini Mushrooms"),
top19 = Topping.create(name: "Egg"),
top20 = Topping.create(name: "Eggplant"),
top21 = Topping.create(name: "Extra Cheese"),
top22 = Topping.create(name: "Extra Sauce"),
top23 = Topping.create(name: "Extra Virgin Olive Oil"),
top24 = Topping.create(name: "Feta Cheese"),
top25 = Topping.create(name: "Fior di Latte"),
top26 = Topping.create(name: "Fresh Basil"),
top27 = Topping.create(name: "Fresh Chilies"),
top28 = Topping.create(name: "Fresh Clams"),
top29 = Topping.create(name: "Fresh Garlic"),
top30 = Topping.create(name: "Fresh Mozzarella"),
top31 = Topping.create(name: "Gaeta Olives"),
top32 = Topping.create(name: "Gorgonzola"),
top33 = Topping.create(name: "Green Bell Peppers"),
top34 = Topping.create(name: "Green Olives"),
top35 = Topping.create(name: "Ham"),
top36 = Topping.create(name: "Hot Cherry Peppers"),
top37 = Topping.create(name: "Jalapeño"),
top38 = Topping.create(name: "Kalamatta Olives"),
top39 = Topping.create(name: "Kale"),
top40 = Topping.create(name: "Lemon"),
top41 = Topping.create(name: "Meatballs"),
top42 = Topping.create(name: "Mushrooms"),
top43 = Topping.create(name: "Olives"),
top44 = Topping.create(name: "Onions"),
top45 = Topping.create(name: "Oregano"),
top46 = Topping.create(name: "Parmigiana"),
top47 = Topping.create(name: "Parsley"),
top48 = Topping.create(name: "Pear Tomatoes"),
top49 = Topping.create(name: "Pecorino"),
top50 = Topping.create(name: "Pepperoncini"),
top51 = Topping.create(name: "Pepperoni"),
top52 = Topping.create(name: "Peppers"),
top53 = Topping.create(name: "Pesto"),
top54 = Topping.create(name: "Pineapple"),
top55 = Topping.create(name: "Potatoes"),
top56 = Topping.create(name: "Porcini Mushrooms"),
top57 = Topping.create(name: "Primo sale"),
top58 = Topping.create(name: "Red Onion"),
top59 = Topping.create(name: "Ricotta"),
top60 = Topping.create(name: "Roasted Garlic"),
top61 = Topping.create(name: "Salt Cured Olives"),
top62 = Topping.create(name: "Sausage"),
top63 = Topping.create(name: "Sautéed Garlic Spinach"),
top64 = Topping.create(name: "Sautéed Spinach"),
top65 = Topping.create(name: "Scallions"),
top66 = Topping.create(name: "Sea Salt"),
top67 = Topping.create(name: "Smoked Pancetta"),
top68 = Topping.create(name: "Soppressata"),
top69 = Topping.create(name: "Speck"),
top70 = Topping.create(name: "Spicy Salami"),
top71 = Topping.create(name: "Spinach"),
top72 = Topping.create(name: "Sun-Dried Tomatoes"),
top73 = Topping.create(name: "Sweet Roasted Red Peppers"),
top74 = Topping.create(name: "Sweet Sausage"),
top75 = Topping.create(name: "Thyme"),
top76 = Topping.create(name: "Tomato"),
top77 = Topping.create(name: "Truffle Pate"),
top78 = Topping.create(name: "White Anchovies")
